version: '3.8'

services:
  airflow:
    container_name: airflow_standalone
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./dags/:/opt/airflow/dags/
    command: "standalone"
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
        - "4566:4566"
    environment:
        - SERVICES=sqs,s3,iam
        - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
