version: '3.8'

services:
  jupyter:
    container_name: jupyter_lab
    build:
      context: .
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work
    networks:
      - data-eng-network

networks:
  data-eng-network:
    external: true
